### ISSUE TITLE
Add some FA:S clientside settings to the F1 Menu

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/BattleRoyaleIssues#102]
Disable HUD elements? `fas2_nohud (default: 0)`
Use custom HUD elements? `fas2_customhud (default: 1)`
Use hold-to-aim? `fas2_holdtoaim (default: 0)`
Use alternative bipod behavior? `fas2_alternatebipod (default: 1)`
Use blur effects? `fas2_blureffects (default: 0)`
BLUR: Depth blur? `fas2_blureffects_depth (default: 0)`
Enable hitmarker? `fas2_hitmarker (default: 0)`
**Reset settings to default** `fas2_resetsettings`

**Comment by Donkie** [comment]
Done
