### ISSUE TITLE
Knife/machete changes

### ISSUE THREAD

**Issue by ViralDevinity** [GMDevinity/BattleRoyaleIssues#109]
### Knife
- Remove the ability to backstab unless you're crouched down (delay crouching to prevent abuse of this).

- Reduce Left-click damage to 30-35(?), there isn't much of a difference between left click and right click and that shouldn't be the case.

- If you can; make the stabbing more consistent, it's annoying being stabbed by someone who isn't even in range of you just because you're closer to them on their screen. 

### Machete 
- Increase right click damage to 70-75(?) it's a machete, it shouldn't be comparable to the knife. 

- Increase left click damage to 50-55(?) reason above.

**Comment by Zzoppa** [comment]
I did not see where that is, but it's still possible for **Machete** to just replace the knife, instead of being placed in a separate inventory slot

**Comment by Donkie** [comment]
Fixed most of these
