### ISSUE TITLE
The Robot Dance Gesture making you Bulletproof

### ISSUE THREAD

**Issue by Hangaroid** [GMDevinity/BattleRoyaleIssues#110]
Today while I was playing Battle Royale, I pressed B, which is my bind for the Robot Dance, because I was obviously gonna lose a shootout so might as well dance it out and what happened is that he could not shoot out the last 10% of my health (He was pretty close to me as well, it was not just bad aiming) which I found really funny at first, but decided to just report it since it is an issue considering it can be used to give one an advantage. I haven't had a chance to test the other gestures and/or whether grenades and the sphere can do the damage.

**Comment by Hangaroid** [comment]
Just an update, apparently some hitgroups take damage and some don't. I was testing it out a lot today and found the issue quite interesting and I would suggest that someone sees it for themselves.

**Comment by Donkie** [comment]
Can't really fix, there's nothing saying that damage should be prevented while doing gestures in the code, so this is a model issue, which I can't really mess with.
