### ISSUE TITLE
Remove BR EU2 server

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/BattleRoyaleIssues#113]
It's just laggy and people should be well aware of EU1 by now.  
Make it immediately redirect people who join it for a month, then we can permanently close it.

Should also look into opening up another server on the devinitypower box perhaps

**Comment by SergeantOrange** [comment]
I advise, 1 week of redirect, then close the server for 1 day to see that the eu2 players have moved over to eu1 for good or not, if its going well then just have a redirect for the rest of the 3 weeks then shutdown the server, if not then we reconsider.

**Comment by manchyy** [comment]
wouldn't it just be easier to make it when people connect give them disconnect reason with "EU2 Closed, join EU1 instead."?

**Comment by AOBatch** [comment]
^ ruskies
