### ISSUE TITLE
Supply drops

### ISSUE THREAD

**Issue by manchyy** [GMDevinity/BattleRoyaleIssues#114]
Supply drop system would be cool. And I know there is a thread somewhere buried that is named like this, but I really want it to happen and I think this is more detailed in general.

_How would it work_

- A plane would fly over the map, picking place the place for an airdrop randomly. 

- If we don't want to go with a plane we could try going with something different. For example [this](https://www.youtube.com/watch?v=oN0dnxpBZpQ).

- The location of an airdrop would appear on the minimap. _(to prevent confusion and to make it easier to find)_

- It could show the location like [this](https://imgur.com/a/Bk54T). Maybe make it "Drop"

- Since rounds aren't long, making the airdrops rare (such as 0.25 to spawn in)

_What could it contain_

- RPG-7 [workshop link](https://steamcommunity.com/sharedfiles/filedetails/?id=541587623) _(Add variety to the game and for the vehicles (if they will ever be added) in the future)_

- Smoke grenades _(For more tactics)_

- Shotgun _(Remington 870, pump-action)_

- Helmet _(Would block one instance of damage or reduce the damage to 50% for once)_

- Very tiny chance of containing a coin booster

- SR-25 Semi-Auto Sniper Rifle

**Comment by Donkie** [comment]
#94

**Comment by Donkie** [comment]
Coins
