### ISSUE TITLE
Fix the bridge at Docks

### ISSUE THREAD

**Issue by ViralDevinity** [GMDevinity/BattleRoyaleIssues#123]
### Wooden bridge at lighthouse connecting to docks
The collisions on the bridge are horrendous, it's like a gamble if you jump or run across it as it'll sometimes send you flying off of it into the water below.
A way to fix this would be to remove the bridge and add a more consistent replacement or just fix the existing bridge with better collisions.

**Comment by Donkie** [comment]
One issue per issue please

**Comment by Donkie** [comment]
Unless you have any better prop suggestions, I think the best way to fix it is by covering it with an invisible, long and smooth prop.
