### ISSUE TITLE
Add Remington 870 to game 

### ISSUE THREAD

**Issue by bjincy** [GMDevinity/BattleRoyaleIssues#125]
After conferring with other staff, we would like the 870 from FAS:2 (the weapons pack already used) to be added to the game on a trial period.  The spawn rate should be the same as the m-82 for now, and can be adjusted based on its performance.  it should come with 12-16 shells (1 1/2 to 2 clips of ammo). After using it in various ways on single player, it is my belief that it will not be overpowered, but will add a new element to the game, hopefully keeping people moving in town and factory instead of camping.

**Comment by AOBatch** [comment]
Every gun spawns with 2 clips of ammo but yes i'm down. Also Mac10 pls
