### ISSUE TITLE
Break large teams when online players decrease

### ISSUE THREAD

**Issue by bjincy** [GMDevinity/BattleRoyaleIssues#129]
Currently, when there are 15 people on the server you can create a three person team.  To make a 4 person team you need 25(?) People on the server and so on.  The problem is that when the server falls below the set level (let's say 25) a 4 person team can remain, and has even lead to 4v1 matches that hurts the playerbase.  After discussing with other staff, I believe 3 person teams should be allowed until 7 or 8 people are left so friends aren't split but every other tier should break once the playerbase has fallen 3-4 people below the limit.

**Comment by Donkie** [comment]
Done
