### ISSUE TITLE
Velocity kill player movement after 6 or more consecutive hops

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/BattleRoyaleIssues#137]
Bhopping is a big and apparent issue that is not obviously not condoned here judging from discussions. Instead of permanently banning players for such a (minor) issue, one of these proposed options should be implemented:

**Reduce the player's velocity speed** (or add a speed cap)
- By half after bhopping 6 consecutive times (most common jumps people have made by using just scroll wheel)
- if the player has reached X amount of velocity (like those CSGO surf servers; speed cap should be 1.5x the speed you get from running and jumping [350 on flat surfaces but **375* should be bare maximum)
- By 1/10th for every jump

This will allow staff to focus their attention more on actual cheaters who taps heads perfectly and reduce the amount of potential bans of those with legitimacy from people with actual bhop hacks, scripts, macros or whatever else may be the case

**Comment by Donkie** [comment]
Added an anti-bhop script
