### ISSUE TITLE
Team tool

### ISSUE THREAD

**Issue by SirJuanCarlos** [GMDevinity/BattleRoyaleIssues#146]
Mods need a tool, which allows them to move people into teams. This would eliminate people getting slayed because of teaming

**Comment by Donkie** [comment]
That's a good way to solve trucing, will do

**Comment by Donkie** [comment]
I've made an admin command `d_forcecreateteam <ply1> <ply2> (<ply3>) (<ply4>)` be available to jr+. It's not a fully fledged tool but it's something.
