### ISSUE TITLE
Team system

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/BattleRoyaleIssues#15]
- This would encourage people to not truce
  - You can only edit teams in pregame and before you've dropped from the plane
  - Max team size would depend on amount of players on the server
  - Teammembers can see each other in the minimap
  - Teammembers have a more noticable target ID HUD on their teammembers
  - Friendlyfire will still be on!
  - Teams automatically disband after the round is over
  - If there's only one team left in the round, the team is automatically disbanded and the members get a notification that they **need** to kill each other (there must always be only one player left)

**Comment by CounterCraftz** [comment]
- Team members will only be able to spectate other team members (to reduce ghosting) --> staff members are exempt from this
