### ISSUE TITLE
Airdrops suggestions

### ISSUE THREAD

**Issue by SirJuanCarlos** [GMDevinity/BattleRoyaleIssues#152]
Airdrops shouldnt spawn every round rather 1:3 rounds
Add the SR-25 to the airdrops?
 -lower the damage from 55 - 40?

 (fix M79 kills not showing up in the killfeed and on the scoreboard)

**Comment by AOBatch** [comment]
Lower the damage of what?
If we decreased how often the airdrop spawned it should be random and not just every three rounds. We could base its probability on how many players are alive

**Comment by SirJuanCarlos** [comment]
(The SR-25 has a base damage of 55 and I would decrease it to 40)
Also thats exactly what I meant.1:3 not every third round. (Kind of like events in Flood but more common)

**Comment by bjincy** [comment]
I think the sr-25 should have the same damage as the m-24 personally

**Comment by SirJuanCarlos** [comment]
Its 1 shot headshot and 2 shots for the body. It has 10 rounds. You want it to be a SNIPER not a RIFLE. with 40dmg it would be 2shot headshot and 3 for the body.

**Comment by Donkie** [comment]
Too vague request
