### ISSUE TITLE
New system for flood

### ISSUE THREAD

**Issue by ghost** [GMDevinity/BattleRoyaleIssues#154]
I'm not sure if this is a good suggestion but:
Would adding a system where you earn a lot more money when you spend more on your boat?
Just enough to prevent people from farming. Eg. you'd earn more if you made a proper boat than to use small boats
This wouldn't stop people who are poor from using the free prop to regain their money back
But to try and stop people from farming by making a 2 prop boat next to a team with a giant boat and just spraying them down with explosives and m249s 
This might influence people to make proper boats(edited)
Sortta like betting:
you spend more
You can earn more

**Comment by AOBatch** [comment]
Can we have an actual idea rather than a concept? We already know this is an issue and want a fix but you haven't actually suggested anything.

This is in BR suggestions btw
