### ISSUE TITLE
Ghillie suit model is broken

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/BattleRoyaleIssues#158]
```
Item "ghillie": $modelname doesn't match model path, will cause issues.
$modelname:	"models/stalkertnb/sunrise_symmetry.mdl"
Path:		"models/stalkernb/sunrise_symmetry.mdl"
```

Either replace it with a different model, or repackage it to our own addon.

**Comment by CounterCraftz** [comment]
Can we use the ghille suit from flood?

**Comment by Donkie** [comment]
@CounterCraftz sure

**Comment by CounterCraftz** [comment]
Also added pilot plymdl to br content 1

**Comment by CounterCraftz** [comment]
@Donkie can you also unmount these from the collection?
https://steamcommunity.com/sharedfiles/filedetails/?id=232636218 (already in the main content)
https://steamcommunity.com/sharedfiles/filedetails/?id=428102413
