### ISSUE TITLE
flashlight stays on when spectating

### ISSUE THREAD

**Issue by bjincy** [GMDevinity/BattleRoyaleIssues#159]
if you die with your flashlight on and spectate someone it stays on, giving away their position.

![20180723015216_1 - copy](https://user-images.githubusercontent.com/38669838/43059835-612db75c-8e1c-11e8-941b-63f320493978.jpg)
![20180723015150_1](https://user-images.githubusercontent.com/38669838/43059836-613e4e50-8e1c-11e8-94c0-f1a3a0f71046.jpg)

**Comment by Donkie** [comment]
Attempted fix, please update me if it works
