### ISSUE TITLE
Increase booster durations to 10 days

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/BattleRoyaleIssues#163]
I don't think 1 week is exactly worth for any real currency purchases given the circumstancethat the playerbase dwindles around EU nighttime and especially at US

it might be worth nothing that maybe it would be ideal for the booster to count down ingame time instead of real like on the poll that we did >6 months ago but it still doesn't really encourage players to stick around as much

**Comment by Donkie** [comment]
I don't think any of these ideas will make people stay longer.
