### ISSUE TITLE
Supply drop items sometimes collide through the floor

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/BattleRoyaleIssues#164]
![image](https://user-images.githubusercontent.com/11022368/45256558-f6e3e780-b365-11e8-92a4-07ec72ab59a5.png)

Supply drop was at the cabin near the lakes and I wasn't able to find some items until I noclipped below the map

**Comment by Donkie** [comment]
Pretty rare event and i cba fixing it
