### ISSUE TITLE
Supply drop weapons

### ISSUE THREAD

**Issue by bjincy** [GMDevinity/BattleRoyaleIssues#166]
I feel like these should be the supply drop weapons
M-82
M-79
M-67
M3-Super 90 (6 shell tube, 12 shells total)
RPK-47 (2 45rnd magazines)(27 damage)
SR-25 (2 5rnd magazines)(same damage and spread as M-24)
Wakizashi (maybe 60 damage per body hit and a longer reach?)

other than the M-82 and M-67, they should be limited to the crates only.  They will be Mildly OP, but that is to pay off the risk of getting the box.

**Comment by Donkie** [comment]
Currently the supply drops consist of different packs, can you maybe come up with some new ideas?

![image](https://user-images.githubusercontent.com/2332094/45269706-7f5fa680-b492-11e8-8666-ec1bc25f3793.png)

**Comment by bjincy** [comment]
make sr-25 same as m-82, replace 870 with super90. RPK should be same as m79, Wakizashi is an interesting one, I feel like it should be the same as the 870 with the grenade.

**Comment by SirJuanCarlos** [comment]
My suggestions:
nerf helmet to +30 hp
add a vest that gives you +50 hp
The heavy kit:
RPK 47 
Vest
Coins
Medkit

**Comment by bjincy** [comment]
I like the vest idea

**Comment by bjincy** [comment]
After testing, super90 is good for now, but the slugshot "attachment" should be removed.  The rpk seems good, may need balancing later.  The debate is still out on the sr-25, starting at 60dps for body shots should work and we can pull that back some after seeing it in action

**Comment by Donkie** [comment]
this whole issue is way too vague for me to do something concrete with
