### ISSUE TITLE
Optimization commands 

### ISSUE THREAD

**Issue by ViralDevinity** [GMDevinity/BattleRoyaleIssues#171]
Allo, settings in the F1 menu to enable multicore rendering would be pretty useful, since Garry's Mods is broken putting "gmod_mcore_test 1; mat_queue_mode -1; cl_threaded_bone_setup 1" into the console helps out quite a bit with FPS, making this more accessible to users by placing it in the settings to run the command would probably help a lot of people. 
Maybe a command to also hide the skybox or some shit, dependant on if that would affect gameplay or not.

These could also be applicable to flood.

**Comment by Donkie** [comment]
Done
