### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by wasplay** [GMDevinity/BattleRoyaleIssues#175]
[ERROR] gamemodes/gmbr/gamemode/modules/serverlist/cl_serverlist.lua:121: attempt to index a nil value
  1. UpdateTxt - gamemodes/gmbr/gamemode/modules/serverlist/cl_serverlist.lua:121
   2. AddServerToServerList - gamemodes/gmbr/gamemode/modules/serverlist/cl_serverlist.lua:125
    3. func - gamemodes/gmbr/gamemode/modules/serverlist/cl_serverlist.lua:172
     4. unknown - lua/includes/extensions/net.lua:32

I don't remember when it happened

**Comment by Donkie** [comment]
Thank you for reporting this @wasplay

**Comment by CounterCraftz** [comment]
Happens on flood too
