### ISSUE TITLE
Remove endzone positions inside of the factory

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/BattleRoyaleIssues#42]
![shit](https://steamuserimages-a.akamaihd.net/ugc/868489617103176062/B3FA96566A76BCBCA95B61A6B31DADA0D87EF516/)
![shit](https://steamuserimages-a.akamaihd.net/ugc/868489617103171709/A15EB8CFEFAE612C8F7DD9BF06E4D76A0E5CB096/) 

The barrel models inside of the warehouse are conflicting with the endzone positions that uses the model and it's gay to have them positioned there

very confusing

**Comment by Donkie** [comment]
you know what's funny, it's because we used these this barrelmodel for positioning the spheres. nobody intended for the sphere to spawn there lol

**Comment by Donkie** [comment]
I've removed 7 accidental sphere spawns, we should probably do a little effort to put out a few more now instead.
