### ISSUE TITLE
some hud ideas

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/BattleRoyaleIssues#45]
Team placement

![br3](https://user-images.githubusercontent.com/11022368/30773903-3a78e6bc-a048-11e7-8a32-0c048ca881df.png)
![br4](https://user-images.githubusercontent.com/11022368/30773904-3bd01eb8-a048-11e7-96ab-d49ead6cd686.png)
![br6](https://user-images.githubusercontent.com/11022368/30773950-32a7f1fc-a049-11e7-8299-d71fef5eccaf.png)
_________________
Round Info:
Prepare to deploy. --> 0:30
Scavenge & fight. ---> 2:00 (around)
Get to the sphere. ---> 2:30 (around)
Fight! -----------------> -0:01 (counts up)
Restarting the round. > 0:10 (roundstats pop up)

Voice:
**Alive**
Global
Team
Mute (with a red cross on speaker icon)

**Dead**
Dead
Global (Staff)
Mute

Hints should pop up whenever changing voice channels
![sound](https://devinity.org/flood/icons/silkicons/sound.png) Voice channel has been set to: Dead (should automatically tell players whenever they're dead so they know they cant speak globally)
![sound](https://devinity.org/flood/icons/silkicons/sound.png) Voice channel has been set to: Mute

**Comment by Donkie** [comment]
I don't really like the round info thing we have in flood, so moving it over to here isn't gonna make me like it more. I think it's fine as it is atm.

What's the point of mute voice channel?

Are you sure the oxygen bar is visible enough?

**Comment by CounterCraftz** [comment]
the purpose of the mute vc is if people wants to opt out of voice channels meaning if they don't want to hear other people (like in NA)

now that i think about it, i think it's best if players could toggle voice in F1 instead of the mute channel along with other possible settings (if applicable) 

Muting via settings should exclude staff from this

i wasn't sure about the oxygen bar either but there could be a notifi. on the middle stating that the player is drowning with some effects. if not then it's fine as it was 😛

**Comment by Donkie** [comment]
Most of this is already implemented and the rest is obvious or denied.
