### ISSUE TITLE
access points/blockages ideas

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/BattleRoyaleIssues#47]
1) ![hl2_2017-09-24_13-48-04](https://user-images.githubusercontent.com/11022368/30785956-abdacbc8-a13c-11e7-8edf-d71ba87510ac.jpg)
2) ![hl2_2017-09-24_13-48-33](https://user-images.githubusercontent.com/11022368/30785957-ad43bd94-a13c-11e7-914a-70c51ca3e5de.jpg)
3) ![hl2_2017-09-24_13-48-44](https://user-images.githubusercontent.com/11022368/30785958-b081f412-a13c-11e7-9351-b9c0454fd14b.jpg)
4) ![hl2_2017-09-24_13-49-05](https://user-images.githubusercontent.com/11022368/30785959-b1c1acf0-a13c-11e7-9797-93bb771d3f6c.jpg)
5) ![hl2_2017-09-24_13-49-16](https://user-images.githubusercontent.com/11022368/30785960-b360a426-a13c-11e7-8737-b73b0a1e1c56.jpg)
6) ![hl2_2017-09-24_13-49-23](https://user-images.githubusercontent.com/11022368/30785963-b72f7be0-a13c-11e7-9c4c-e3869aac6606.jpg)
7) ![hl2_2017-09-24_13-49-46](https://user-images.githubusercontent.com/11022368/30785964-b8ce9e4a-a13c-11e7-9e78-48af2acd748a.jpg)
8) ![hl2_2017-09-24_13-51-01](https://user-images.githubusercontent.com/11022368/30785965-ba478f7a-a13c-11e7-915e-539b20ef702a.jpg)
9) ![hl2_2017-09-24_13-51-43](https://user-images.githubusercontent.com/11022368/30785966-bb9c31aa-a13c-11e7-89ae-d46e755fae50.jpg)
10) ![hl2_2017-09-24_13-53-19](https://user-images.githubusercontent.com/11022368/30785967-bd326638-a13c-11e7-8c8e-d727319a92e1.jpg)
11) ![hl2_2017-09-24_13-53-28](https://user-images.githubusercontent.com/11022368/30785969-bf33e8b2-a13c-11e7-8323-924812954055.jpg)
12) ![hl2_2017-09-24_13-56-55](https://user-images.githubusercontent.com/11022368/30785972-cc4f0612-a13c-11e7-9d90-3879ed9d3c02.jpg)
13) ![hl2_2017-09-24_13-57-44](https://user-images.githubusercontent.com/11022368/30785975-cfb83648-a13c-11e7-90ff-a30ae2097cb4.jpg)
14) ![hl2_2017-09-24_13-58-16](https://user-images.githubusercontent.com/11022368/30785976-d15103ea-a13c-11e7-8e86-37d8dc7370ea.jpg)
15) ![hl2_2017-09-24_15-48-30](https://user-images.githubusercontent.com/11022368/30786173-f31ccd94-a13f-11e7-9244-b7b7c9fc740a.jpg)

**Comment by CounterCraftz** [comment]
not sure if we need more than 2 accesses for the factory (10 11 and 13)
not sure about 11 either

- players usually forget that theres a road behind the little roof
- players are unable to access the roof because of the sphere --> only possible way is the road

**Comment by Donkie** [comment]
hit me up when u guys wanna position shit for this

**Comment by CounterCraftz** [comment]
Can we do this sometimes during the weekend (saturday preferably)?

This addon would be very beneficial for us
https://steamcommunity.com/sharedfiles/filedetails/?id=105955548

**Comment by Donkie** [comment]
Yeah sure

**Comment by CounterCraftz** [comment]
voided adding staircases to the lighthouse
