### ISSUE TITLE
Team issues

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/BattleRoyaleIssues#52]
- [x] add team name when spectating
- [x] disable ability to join team after you've deployed

**Comment by CounterCraftz** [comment]
- [x] teams are not properly aligned on scoreboard
> ![hl2_2017-09-29_16-35-13](https://user-images.githubusercontent.com/11022368/31035289-6ed6ec32-a535-11e7-819f-9fe259fcc99a.png)
