### ISSUE TITLE
Remove these boxes.

### ISSUE THREAD

**Issue by mash-xr** [GMDevinity/BattleRoyaleIssues#56]
![image](https://user-images.githubusercontent.com/30399407/31406583-f063361e-adcf-11e7-8bfa-d63e09b16f9e.png)
Posted this in flood first on accident because I can't read. These boxes are in the tunnel directly underneath the church, and if you try to destroy them with a knife they end up killing you half of the time because of stupid physics. I got killed by the boxes twice and Rick did too.

**Comment by CcLLL** [comment]
Also on a side note. When you go into hide on Br you cant see global players.

**Comment by Donkie** [comment]
Done
