### ISSUE TITLE
Golden knife skin 

### ISSUE THREAD

**Issue by bayrock** [GMDevinity/BattleRoyaleIssues#61]
Majority of us agree on the idea of weapon skins in some capacity. The first obvious choice is a golden knife for the top weekly/monthly players.

**Comment by AOBatch** [comment]
@donk when gun skin?

We had the same idea when we had JB but idk guess it's not an easy thing to implement. Hopefully the fact that the gamemode is popular will encourage you to do it eh donkrs. Or maybe bayrock can do it :)))

**Comment by CcLLL** [comment]
Are we just talking about weapon skins.? Or are we also talking about player models?
