### ISSUE TITLE
Spastic scoreboard

### ISSUE THREAD

**Issue by CcLLL** [GMDevinity/BattleRoyaleIssues#63]
-The spastic scoreboard issue is still going on after prefix.

-Also would it be possible too add a slap command that dose no dmg for staff so you dont have too teleport/goto them too get them out of when they are stuck or such.

**Comment by CounterCraftz** [comment]
![asdasd](http://f.devinity.org/DDTuuf)

**Comment by CcLLL** [comment]
That's what i'm talking about it's still going after the hotfix

**Comment by Donkie** [comment]
Has anyone seen this happen to alive players?

**Comment by CounterCraftz** [comment]
Yeah, it's been doing this regardless of (any) status

**Comment by Donkie** [comment]
finally fixed
