### ISSUE TITLE
Add "Map" tab on F1

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/BattleRoyaleIssues#65]
Many players have been asking this feature to be implemented

![brmaps](https://user-images.githubusercontent.com/11022368/32702871-27731c96-c7bb-11e7-90fa-5578f2baece8.png)

**Comment by Donkie** [comment]
what about having the minimap get big if you press M, then small if you press M again?
maybe also have location names placed out on the big map, like "church", "city", "light house" etc

**Comment by CounterCraftz** [comment]
I thought about that but was like, maybe everything should be placed into the F1 menu, just like what we did in flood

Pressing M is just as simple as F1 which automatically opens up the maps tab so it's very convenient

**Comment by Donkie** [comment]
The F1 menu shouldn't be that tightly connected to the gameplay. When the game starts, you shouldn't need to use the F1 menu, it's abit clunky imo. Also having the map enlarge on M key is very common already in games so people will feel at home with that.
