### ISSUE TITLE
Custom hints/ads

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/BattleRoyaleIssues#7]
Could add hints here until we have a database setup

**Comment by CounterCraftz** [comment]
Visit our forums in-game by typing /forums | world
Visit our forums in-game by typing /forums | world
Purchase Bronze, Silver, Gold, or Platinum benefits to support the server! | heart
Purchase Bronze, Silver, Gold, or Platinum benefits to support the server! | heart
Check our forums for updates; we are developing frequently! | computer
Check our forums for updates; we are developing frequently! | computer
Staff applications can be made after signing in at https://devinity.org | pencil
Staff applications can be made after signing in at https://devinity.org | pencil
Click a player in the scoreboard to see all their info! | vcard
Click a player in the scoreboard to see all their info! | vcard
Right click a player in the scoreboard to view options | mouse
Right click a player in the scoreboard to view options | mouse
Have a question, suggestion, or problem? Visit https://devinity.org | information
Have a question, suggestion, or problem? Visit https://devinity.org | information
Sign up on our forums and receive in-game rewards! | award_star_gold_1
Sign up on our forums and receive in-game rewards! | award_star_gold_1
Use !requestban <playername> to open up a form for requesting a ban! | report
Use !requestban <playername> to open up a form for requesting a ban! | report
Add us to your favorites! | star
Add us to your favorites! | star
Join our discord server to interact with players/staff and view changelogs at https://devinity.org/discord | group
Join our discord server to interact with players/staff and view changelogs at https://devinity.org/discord | group
You can add color to your name by adding tags like [red], [blue] etc. COD:MW2 style tags are also supported! | palette
