### ISSUE TITLE
Improved spectator mode after death???

### ISSUE THREAD

**Issue by Zzoppa** [GMDevinity/BattleRoyaleIssues#77]
The idea is: After your death, you can monitor the players, and when you look at the player from the team (for example, a team of two players), then you see another players from this team on the map. It seems that "And what?", Well, it seems to me that it can be used for monitoring, for example, you are with someone in the team, and you were killed, you can tell teammate whether the player is coming from another player, or not. In general, what I want to suggest is to make sure that other players who are outside of the team can not watch all the players who are in this team on the map.

**Comment by Donkie** [comment]
late but, only jr+ sees everyone on minimap
