### ISSUE TITLE
Change the way 'good spots' work

### ISSUE THREAD

**Issue by AOBatch** [GMDevinity/BattleRoyaleIssues#80]
Good weapon spawns are broken and give way too much of an advantage, if we want to keep the idea then we should make them just have a better chance to spawn assault rifles etc, but they should still spawn pistols etc. The M82 and grenades should also be added to normal spawns just with a very low spawnchance

**Comment by Donkie** [comment]
So all weapons should be spawnable on the good spawns but the good weapons should still have a rather high chance?
Currently the M82 has 25% chance on a good spawn for example, how high chance should it have after the change? How high chance on normal spawns?

**Comment by AOBatch** [comment]
Maybe 1% or so on normal spawns, if you want me to do a table for good spawns I can

Also we should change the damage for M82 to 100, so that legshots are non fatal. RN it's broken af

**Comment by Donkie** [comment]
Well the fun part of it was that it's supposed to be one hit kill, but it should be more rare. Perhaps be moved to air drops whenever that's added.

**Comment by AOBatch** [comment]
Well it's pretty easy to noscope people is the issue, you should at least have to aim at their chest to get a kill. Also you should get 3 or 4 bullets total, right now it's 6 as you set the clipsize to 3 and you still get two clips

**Comment by Donkie** [comment]
I see, yeah good idea

**Comment by SilverDrMario** [comment]
So wait you want the M82 to get nerfed and have it be a rare spawn?  1% is wayyyy too low and you'll never see it in good spawns, I would say like 10% would be the lowest to go if it's at a good spawn.

**Comment by ghost** [comment]
I think 25% chance on a good spawn is a bit too much.  I don't know how many good spawns there are, but that's 25% chance you'll see the gun that 1 shots anyone at good locations.  I would decrease the spawn rate to like 15-20% at good spawns, because the weapon is just far too good for being so common at good spawns.
