### ISSUE TITLE
Can't change playermodel in-game BR?

### ISSUE THREAD

**Issue by ghost** [GMDevinity/BattleRoyaleIssues#82]
For some odd reason I can't change my PM in battle royal.  Anyone else have this bug who is a mod?  Maybe because I joined the server in !hide?

**Comment by Donkie** [comment]
Could definitely be a hide issue

**Comment by ghost** [comment]
Just reproduced it.  So here's how it works:

You join a server non-hidden, everything is fine even after you !hide.
You join the server hidden, you can't change the player model even after you unhide.
