### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by CcLLL** [GMDevinity/BattleRoyaleIssues#83]
I think it would be a good idea too reduce our max players on Br.
This is starting too be a big problem and i think it's a big turn off for new players who joined the server for the first time. 

When i see 40-45+ players on the ping on everyone gose up to 250-300 on everyone for a good 3min untill 50% of the playersbase is dead.

So my suggestion would simply just too reduce the player limit down too 32-36 players, that way we can also force people too join the US instead we only have 1 server that's being played on.

**Comment by CounterCraftz** [comment]
I believe the 64 cap ~~is~~ was good as is, it's just that EU Flood and BR share the same box which takes up a lot of memory. If the new box is more powerful than the current one we have then I think the cap should be raised back up. 

I don't think anyone would like to join the BR US if there's barely any players supporting it

**Comment by bayrock** [comment]
We've purchased a much more powerful machine with a more robust infrastructure. The new Battle Royale EU 1 server is running on this now. Most of us have witnessed a huge leap in the performance as a result. 

We have also lowered the player count of the old server, and plan to test with our Flood in the near future.
