### ISSUE TITLE
Longer rounds

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/BattleRoyaleIssues#95]
Currently rounds last around 7-8 minutes. If the rounds were longer (20 - 30 minutes) I think there'd be even more tension in the gameplay. People would be more cautious of their life.

With this we also need to add more shit to do other than finding guns.
We also need to add activities for spectators so they want to stick around for the next round.

Post ideas here and what you think

### What new elements could be added for alive players that would make longer rounds more entertaining?
* Airdrop, check #94 
* Pickupable items aimed at a more survival theme, with that we'd also remove the default medkit
* Traps
* Very minor base building shit? (Have to find a turret and some metal or some shit to create a base defence MG)

### What could spectators do while waiting for new round?
* Fishing, could be fun af with leaderboards n stuff
* Spectator DM, check #36 
* Chess

**Comment by Donkie** [comment]
Just realised, if rounds were longer maybe we can let joining players join an existing round if it hasn't gone too far? (maybe if like >50% of players are still alive or something)

There'd of course be a system to prevent dead players from rejoining and reentering.

**Comment by CounterCraftz** [comment]
Regardless if we allow people to join mid-game, people who died early in the game would not like to wait 30 minutes just to get into the next round--I personally wouldn't want to wait either. I don't feel like it would be effective enough to keep players doing spectator-related activities

The majority of the server gets killed by the time ~5 minutes starts to kick in

I feel like we should start focusing on to persuade players to keep getting invested (involved, active) into the game so we can potentially get actual community members from there, or just to make the gamemode enjoyable in general.

**Comment by Donkie** [comment]
Yeah you're right I guess. Could leave this in for future ideas.
