### ISSUE TITLE
Item system

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/BattleRoyaleIssues#97]
Me and rick thought this shit up.
This system will reward player accessories and things like weapon skins etc, no gameplay changing stuff.

During the round you get awarded with "gambling coins" (name pending) for things like killing, achievements, winning round etc.
* 1 coin per kill
* 2 coins per achievement
* 2 coins per level up
* ½ or ⅓ coin per player you won over for winning a round, split between team members

VIP players will recieve more coins based on VIP level.

Once the round is over you can spend these coins on basically a slot machine. You need 20 coins to play and there's 5% chance of winning something. (0.25% / coin)
Or you can spend like 50 coins to play for a more rare and valuable item, with like 1% chance of winning.

You get a higher chance of winning the more fails you have in a row (a visible counter), once you win, the counter resets. Each fail generates an additional 1% chance of winning.

New players unlock a lot of achievements and gain a lot of levels so they will receive a lot of coins, making the system interesting to them and feeding their gambling addiction 

Items from flood will not carry over, but I believe we should somehow reward flood players in BR. Maybe you can trade flood tokens with gambling coins?

![](https://pbs.twimg.com/profile_images/431384983245033474/EAHvXAlR.jpeg)

**Comment by CounterCraftz** [comment]
I was thinking, maybe forum/steam group reward can be tied with this as well

Join whatever method we would give devinity coins out to or join both (for 1 unboxing or an amount close to the unboxing)
