### ISSUE TITLE
force white chat color on staff members (when dead, spectating)

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/BattleRoyaleIssues#99]
so it's easier to distinguish staff from players--to make us stand out more incase if we got anything important to say or tell so-and-so to stop doing that or whatever

it's fairly difficult getting messages across because we sorta get blended in

**Comment by Donkie** [comment]
pink color indicates that you speak in deadchat and only dead people can hear you
white color indicates that you speak for everyone

You can change your voice mode to global in order to speak to everyone

**Comment by CounterCraftz** [comment]
By default, everyone can see what we type regardless of status
Flood also has this as well, so I assumed it's useful enough to add

**Comment by Donkie** [comment]
That shouldn't be the case. If you're not in global voice mode, you should speak and hear just like any other player.

**Comment by CounterCraftz** [comment]
Sorry if I was being vague but Flood also has the same feature where your chat color would still be white regardless whether if you're dead or not as staff. 

The `*DEAD*` prefix gets added whenever you die/spectate so I'm not sure if the same applies to the color indicator 

If it's not an important feature for Battle Royale to have, then the idea can be scrapped

**Comment by Donkie** [comment]
its because you have global chat turned on in settings

**Comment by CounterCraftz** [comment]
the forced color still applies regardless of setting, status, etc.
was this never to be intended?

**Comment by Donkie** [comment]
nope, thats broken in that case
